version: '3.8'

networks:
  inception_network:

services:
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    networks: 
      - inception_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - '443:443'
    expose:
      - '443'

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql   #/var/lib/mysql is the default directory inside a MariaDB container, it's where the database software stores all of its data
                                        #this line tells Docker that you want to bind mount the /home/rgiambon/data/mysql directory on your host to /var/lib/mysql inside the container.
    secrets:
      - db_root_password  # mount the secret into the container
    networks: 
      - inception_network
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    #create a depedency between the 2 container, db will be launched before
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt

volumes:
  
  mariadb_volume:
    driver: local    #local storage on your host machine
    driver_opts:     #additional details about how Docker should handle these volumes
      type: none     #This tells Docker that you're not creating a new Docker-managed volume, but instead you want to link to existing directories on your host machine
      device: /home/rgiambon/data/mysql  #the actual path on your host machine where the data should be stored
      o: bind        #This tells Docker to bind mount these directories. This means the data will be shared between the container and your host machine, so any change in the container will reflect on the host, and vice versa.
  
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/rgiambon/data/wordpress #I will have to create this directory 
      o: bind

    
