FROM alpine:3.21.4

RUN apk update && \
    apk add --no-cache mariadb mariadb-client

COPY ./tools/script.sh /tmp/script.sh

RUN  chmod +x /tmp/script.sh

ENTRYPOINT ["sh", "/tmp/script.sh"]

CMD ["mysqld_safe"]