FROM debian:buster

RUN apt-get update && \
    apt-get install -y nginx openssl && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
       -out /etc/nginx/ssl/rgiambon_cert.crt \
       -keyout /etc/nginx/ssl/rgiambon_key.key \
       -subj "/C=ES/ST=Barcelona/L=Barcelona/O=42 School/OU=rgiambon/CN=rgiambon/" 
       #last one is domain name

COPY ./conf/nginx_conf.conf /etc/nginx/conf.d

RUN mkdir -p /run/nginx

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]